### ISSUE TITLE
Crash when accessing last page (third) of settngs

### ISSUE THREAD

**Issue by nikobockerman** [TylerWilliamson/QuickWeather#43] opened 2022-09-11 08:58 UTC
QuickWeather 2.2.2 crashes when attempting to enter the last page of settings. I was able to get there once after install so I did set something to the settings that time. But I don't remember which settings I put there and I can't get to that page anymore.

I have installed QuickWeather through F-Droid, in case that matters.

Below is a backtrace of the crash:
```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.220624.021.A1/2022090600:user/release-keys
package: com.ominous.quickweather:46
process: com.ominous.quickweather

java.lang.IllegalStateException: Fragment c{eb5b4f2} (64a2b4e0-cee1-4163-9f05-57ed5534fcb8) not attached to an activity.
	at androidx.fragment.app.n.N(Unknown Source:31)
	at com.ominous.quickweather.activity.SettingsActivity$c.Z(Unknown Source:0)
	at com.ominous.quickweather.activity.SettingsActivity$c.Y(Unknown Source:0)
	at t3.a$a.c(SourceFile:8)
	at androidx.viewpager2.widget.a.c(Unknown Source:18)
	at androidx.viewpager2.widget.a.c(Unknown Source:18)
	at androidx.viewpager2.widget.d.f(Unknown Source:4)
	at androidx.viewpager2.widget.ViewPager2.d(SourceFile:8)
	at androidx.viewpager2.widget.ViewPager2.c(SourceFile:4)
	at t3.a.onClick(Unknown Source:17)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29335)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by TylerWilliamson** [comment] 2022-09-11 15:52
This is a duplicate of #35. Thank you for the bug report, though! I plan to resolve this bug in the next release (2.2.3)

**Closed by TylerWilliamson** 2022-09-11 15:52 UTC
Labels: bug, duplicate
