### ISSUE TITLE
Add marker on radar map for current location

### ISSUE THREAD

**Issue by 0-5-0** [TylerWilliamson/QuickWeather#118] opened 2023-12-29 19:00 UTC
Would it be possible to add a marker on the radar map which highlights the location selected in the app. Since you can't see through the radar map when there's weather events it would help me pin point where my location is during a storm when there's huge clouds up above.

This could be similar to how it's done in apps like Weatherian (android/web). I'm not sure if opacity settings could be added otherwise so that we can see through the clouds/so we can see landmarks/streets below.

Thank you, it's a wonderful app.

**Comment by TylerWilliamson** [comment] 2023-12-30 01:54
This is a duplicate of #40 but since it has been requested repeatedly, I'll reopen #40 and look for a solution

**Closed by TylerWilliamson** 2023-12-30 01:54 UTC
