### ISSUE TITLE
Consider alternatives to proprietary OpenWeatherMap that demands user's credit card to make your app work

### ISSUE THREAD

**Issue by baack** [TylerWilliamson/QuickWeather#75] opened 2023-07-16 14:22 UTC
OpenWeatherMap is currently not **open** at all.

To get minimal OneCall API key OpenWeatherMap all **users must provide all this information**:

* Real name and real address information
* Credit card number and other billing information
* Phone number

So, all this information must be provided  to make your application work. It limits the number of users who would be able to use it.

And all this data is obviously not required from technical point of view, and **it is against real meaning of "open" term and open projects** like **f-droid** that even does not require account to use it, or OpenStreetMaps that gives free and open access to everyone without account to.
So, "Open" in OpenWeatherMap is just a joke.
**OpenWeatherMap is not open and should be avoided nowadays whenever possible.**

There are alternatives that currently are not that bad.
Please consider adding support of visualcrossing or something else:
https://www.visualcrossing.com/weather-data-editions

The API is probably similar:
 https://www.visualcrossing.com/resources/blog/replacing-the-openweathermap-api-with-visual-crossing-weather/

**Comment by TylerWilliamson** [comment] 2023-07-16 14:37
I will consider alternatives, but I will also refute that OpenWeatherMap is not "open".

1. Neither name nor address nor phone number are verified after signing up. I would encourage anyone who does not wish to provide their information to use a pseudonym and their favorite public address and phone number. For example, you may sign up as "baack" who lives as "1600 Pennsylvania Avenue, Washington, DC" with the phone number 123-456-7890.
2. The "credit card" requirement is similarly easy to bypass with a simple gift card.

Regarding your alternative, it too is not "open" by [F-Droid standards]() since it is not "an alternative, publicly available, self-hostable, free software server solution"

**Comment by TylerWilliamson** [comment] 2023-07-16 14:38
I misclicked and accidentally closed this ticket. It will stay open and if I find an alternative, I may include it and update this thread

**Comment by baack** [comment] 2023-07-16 14:45
Thanks for the fast reply. 

1. I was not aware of it, and anyway I am not conformable with providing fake data, I would prefer ability to not provide it in the first place. Especially in the case when it is completely not-technically-required for the provided service.
2. Do they freeze or charge a small amount of money on the card for the verification? Credit card is almost like passport in many countries.

About "open" alternatives. I agree that visualcrossing is also not open nor libre, but they do not use it misleadingly in the name as "open"weathermap does. I am not confident about alternatives (you know better), I just provided the first one that looked reasonable in the search results, it definitely can be not the best choice either, it is true.

**Comment by TylerWilliamson** [comment] 2023-07-16 14:59
Regarding Visual Crossing, it appears that they have a 1000 free limit daily, same as OpenWeatherMap. However, they seem to charge for each hour and day requested. So a typical request by QuickWeather to get the current weather, next 48 hours, and next 7 days would cost 57 on Visual Crossing, but only 1 on OpenWeatherMap. I will still consider including Visual Crossing support if there are enough users wanting it.

Also, OpenWeatherMap does also offer API Keys without "OneCall", and this only requires an email address. However, this tier does not include weather alerts and also requires that I make two API calls to get the current and forecasted weather. I am weighing including this as a data source as it is more "open", but since it does not offer the weather alerts, it can be dangerous to users.

If there are any other data sources that you (or other users) are aware of, please note them in this thread and I will evaluate them

**Comment by baack** [comment] 2023-07-16 15:14
> Also, OpenWeatherMap does also offer API Keys without "OneCall", and this only requires an email address

Well, I tried QuickWeather, it looks nice, but I was not able to get any weather checks because my free account API key was rejected as it is not OneCall-type.

Is it possible to use QuickWeather with "API Keys without OneCall that only require an email address"? It would solve the problem for me. For me current weather and simple forecast is sufficient, because I'm checking weather on the band via GadgetBridge, so alerts are not used in my case anyway.

**Comment by baack** [comment] 2023-07-16 15:18
> I will still consider including Visual Crossing support if there are enough users wanting it.

Note: I am not insisting on Visual Crossing at all, I just though it provides enough requests for free without phone number, credit card number that are obligatory in case of openweathermap.

**Comment by TylerWilliamson** [comment] 2023-07-16 15:21
In the current version of QuickWeather, you cannot use OpenWeatherMap without the OneCall subscription. I am considering implementing being able to use API Keys without the OneCall subscription, but, again, since it does not offer the weather alerts, it can be dangerous to users.

If I implement support for API Keys without the OneCall subscription, or an alternative weather service, I will update this thread.

Note: If you only want to use QuickWeather to update Gadgetbridge, there are [other apps](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Weather#weather-providers), such as "Weather Notification", which uses the OpenWeatherMap API without OneCall

**Comment by baack** [comment] 2023-07-16 15:38
> Note: If you only want to use QuickWeather to update Gadgetbridge, there are [other apps](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Weather#weather-providers), such as "Weather Notification", which uses the OpenWeatherMap API without OneCall

Does not look like it. My free API keys of OpenWeatherMap are not working for some reason. You can check yourself, maybe I am doing it wrong. Also "Weather Notification" was not active for 3+ years, not a good sign.

`Tiny Weather Forecast Germany` is a one that works, but `QuickWeather` looks like a worthy and active alternative, so I decided to make this feature request for it.

**Comment by TylerWilliamson** [comment] 2023-07-16 15:53
Huh, you seem to be right about Weather Notification. I'll avoid recommending it if someone wishes to not use OpenWeatherMap OneCall, but wants to update Gadgetbridge.

**Comment by baack** [comment] 2023-07-16 16:59
> Huh, you seem to be right about Weather Notification. I'll avoid recommending it if someone wishes to not use OpenWeatherMap OneCall, but wants to update Gadgetbridge.

In this case support on OpenWeatherMap with really free (as a beer) API keys (without OneCall) would be a great feature, that is not present in other applications that work for Gadgetbridge.

**Comment by PoepiePeppie** [comment] 2023-07-28 12:46
I don't know if you're already aware of the existance of open-meteo, but it seems to be a better and more free er alternative to openweatermap. I know little about how easy it would be to use it, but it looks promising to me. [https://open-meteo.com/](https://open-meteo.com/)

**Comment by baack** [comment] 2023-07-28 15:08
Looks quite advanced and well-made. They have 10 000 requests per day for non-commercial use. Does it mean that every user has this plenty, or not? It would be great if Tyler would be able to contact them with their nice FLOSS app.

**Comment by TylerWilliamson** [comment] 2023-07-28 15:43
Open Meteo is very interesting. It seems to have most of the data, but is lacking weather alerts.

I think the plan at this point is to have a toggle in the settings for users to use either OpenWeatherMap OneCall, OpenWeatherMap, or OpenMeteo. If users choose a data source without weather alerts, there will be an indicator to make it very apparent. 

If anyone knows of a weather alert data source which is free and covers a significant number of countries, I can use that to augment the other weather sources. This weather alert data is sent out by individual government agencies, which makes it difficult to provide to users.

**Comment by emaen** [comment] 2023-08-03 10:35
Hello, 
Trying to Switch from proprietary weather app to open one, fund yours witch seem perfect,  but unable to use it because of  the "one call subscription" needed !!
 I agree with your Idea of a toggle that permit to switch one call / free / open-météo subscription.
It could be a very good solution.

**Comment by TylerWilliamson** [comment] 2023-08-21 03:45
I wanted to update this thread and inform you all that I have begun work on adding support for Open-Meteo and OpenWeatherMap (without OneCall) in QuickWeather. I hope to release it in the next major version (2.5.0).

I wanted to note a few things about Open-Meteo:
- Open-Meteo is open by F-Droid standards. It is a FOSS application which can be self-hosted (see [their GitHub](https://github.com/open-meteo/open-meteo)). QuickWeather will support self-hosted instances of Open-Meteo as well as the main https://open-meteo.com/
- QuickWeather will also support Open-Meteo users with paid commercial API Keys
- Open-Meteo weather data will be different from OpenWeatherMap. Currently, they chose the "worst" condition for a given hour or day (see [this thread](https://github.com/open-meteo/open-meteo/issues/228)). Practically, this means users will see daily forecasts of "Thunderstorm" and "Fog" even if those conditions occur for a short period of time. I may be able to re-aggregate the daily weather condition in a later release
- Open-Meteo does not provide weather descriptions. I have written English descriptions, but other users will need to translate these to other languages.
- As previously stated, Open-Meteo does not currently provide alert data, but if they provide this data in the future, I will implement support in QuickWeather. They do have an open issue [here](https://github.com/open-meteo/open-meteo/issues/351) regarding adding alerts.

**Comment by baack** [comment] 2023-08-21 03:47
Thanks, you're awesome, man!

**Comment by TylerWilliamson** [comment] 2023-09-11 01:25
I wanted to give another update. I should have a beta version of 2.5.0 coming soon with support for Open-Meteo. However, it will not have support for OpenWeatherMap non-OneCall APIs. OpenWeatherMap simply does not offer free daily weather outside of OneCall. This would mean attempting to calculate daily aggregations of the weather data, including the weather condition, and I do not wish to undertake this effort. If users do not wish to use OpenWeatherMap, they can instead use Open-Meteo for free.

Additionally, I just came across [weatherapi](https://www.weatherapi.com/) which seems to have all of the data needed for QuickWeather, including weather alerts. I'll look into it after releasing the beta 2.5.0

**Comment by TylerWilliamson** [comment] 2023-09-12 00:15
I have released version 2.5.0 with support for Open-Meteo as a [pre=release on GitHub](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.5.0) and as a Beta on [Google Play Store](https://play.google.com/store/apps/details?id=com.ominous.quickweather) (it will take a few hours for the release to be reviewed by Google). I think it will also be available on F-Droid. Please test out version 2.5.0 and let me know of any issues that are found. If all goes well, I hope to fully release this update next week.

As a reminder:
> * Open-Meteo weather data will be different from OpenWeatherMap. Currently, they chose the "worst" condition for a given hour or day (see https://github.com/open-meteo/open-meteo/issues/228). Practically, this means users will see daily forecasts of "Thunderstorm" and "Fog" even if those conditions occur for a short period of time. I may be able to re-aggregate the daily weather condition in a later release
> * Open-Meteo does not provide weather descriptions. I have written English descriptions, but other users will need to translate these to other languages.
> * Open-Meteo does not currently provide alert data, but if they provide this data in the future, I will implement support in QuickWeather. They do have an open issue https://github.com/open-meteo/open-meteo/issues/351 regarding adding alerts.

**Comment by baack** [comment] 2023-09-12 11:47
> Please test out version 2.5.0 and let me know of any issues that are found.

Not sure if I using it right, but `TEST CONNECTION` button is not active when I select Open-Meteo on the second startup screen. 

Otherwise the weather is shown inside the app, but I will have to wait to check how it works with GadgetBridge, because I do not know how to force it to update the weather from your app, looks like it shows some cached weather from other source.

**Comment by TylerWilliamson** [comment] 2023-09-12 12:36
Open-Meteo does not need an API Key or Instance, so by default, it does not need to be tested like OpenWeatherMap, which is why that button is initially disabled

**Comment by baack** [comment] 2023-09-13 15:39
Update after additional tests:
Using `QuickWeather` + `Open-Meteo` without any keys works great for me on band connected with `GadgetBridge`.
I am definitely moving to `QuickWeather` as an app that provides weather to `GadgetBridge`, thanks a lot!

**Comment by PoepiePeppie** [comment] 2023-09-13 20:37
Been using the beta for a couple days now. Its looking real nice. Open-meteo data seems like a good fit for the app. Right now ive only noticed 2 issues. 

1. Clicking on a day in the week will show this screen, but the uv index is not aligned and is lower than the rest of the text. 
![Screenshot_20230913-223029_QuickWeather](https://github.com/TylerWilliamson/QuickWeather/assets/29727357/dd1a0626-4572-417b-86c3-a641d6e36df8)

2. Right now when I select open-meteo I am still able to enable or disable weather alerts. Perhaps this should be grayed out with explanation when the user selects open-meteo to avoid confusion why its not working.
![Screenshot_20230913-223103_QuickWeather](https://github.com/TylerWilliamson/QuickWeather/assets/29727357/85afcbfc-42b3-44d8-8449-11774ddd1137)

**Comment by TylerWilliamson** [comment] 2023-09-13 21:59
Thanks for the feedback. The first issue regarding the daily weather statistics is unrelated to open-meteo, but I will look into it. As for the second issue, I appreciate the suggestion and I will include that in the full release of 2.5.0

**Comment by TylerWilliamson** [comment] 2023-09-16 16:33
Thank you all for the feedback. Version [2.5.1](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.5.1) has been fully released with full support for Open-Meteo.

**Closed by TylerWilliamson** 2023-09-16 16:33 UTC
Labels: enhancement

**Comment by baack** [comment] 2023-09-16 18:38
One more thing I've noticed, not sure if I should report it as an issue yet.

The band connected to `GadgetBridge` shows correct temperature, but the graphical icon is always "Sunny" or something like that: no clouds, only the sun. It is hard for me to understand what is happening, because `GadgetBridge` has no button to fetch and show temperature/weather from the weather provider (your app). So I cannot tell on which step the information is getting always "Sunny".

So, can you please check if there is some obvious problem with a piece of code in the QuickWeather with the interoperability with `GadgetBridge` regarding Sunny/Cloudy/Raining?

**Comment by TylerWilliamson** [comment] 2023-09-16 19:20
@baack Could you open that as a separate issue? I believe the issue is that I translated the Open-Meteo "weather code" to the incorrect OpenWeatherMap "weather code", which is what Gadgetbridge seems to use. It should be a relatively simple fix that I can include in 2.5.2

**Comment by baack** [comment] 2023-09-17 04:20
@TylerWilliamson, will do.
