### ISSUE TITLE
Add Gadgetbridge support

### ISSUE THREAD

**Issue by coxackie** [TylerWilliamson/QuickWeather#38] opened 2022-08-19 13:36 UTC
It would be great to add the possibility of feeding weather data to [Gadgetbridge](https://gadgetbridge.org/). As you can see [here](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Weather), only two apps seem to be doing it, out of which one (`Weather notification`) has not seen any development lately, and the other is quite localised. There has already been effort to do this in `Geometric weather` at [this PR](https://github.com/WangDaYeeeeee/GeometricWeather/pull/329), but it was abandoned due to licencing issues, which do not seem to affect this app. Hopefully, this makes it easier to provide support, if this is something that seems worthwhile.

**Comment by TylerWilliamson** [comment] 2022-08-19 13:51
So I am interested in this. I actually have a Pebble 2, so I could test and make use of this. I'll check the licensing and see if it's possible

**Comment by TylerWilliamson** [comment] 2022-08-20 18:39
So this is absolutely a doable request. As of now, I can use Gadgetbridge to send weather information from QuickWeather to my Pebble 2. However, there are some caveats:

1. I will need to create a pull request for Gadgetbridge. Right now, it doesn't recognize QuickWeather as a weather provider. If I install "Weather Notification", then I can send weather data from QuickWeather as "Tiny Weather Forecast Germany". I'll put together a pull request so that I can do this officially. 
2. Gadgetbridge does not expose its WeatherSpec as an API. I will put in an issue for them to do so. This will allow 3rd-party data providers, like QuickWeather, to have an official way to send data to Gadgetbridge and not rely on copying files between repositories.
3. I only own a Pebble 2. I will need other users to report whether or not there are issues.

**Comment by coxackie** [comment] 2022-08-20 21:24
Hi, and many thanks for taking this up!

1. That's great!
2. Yes, I think you should. Their wiki is also rather uninformative on the subject in general. I think they may have not had a lot of interest on this in general.
3. I can certainly help on this - I have a Mi Band 6 (ethically anti-diametric from your Pebble), and will test when you need.

**Comment by TylerWilliamson** [comment] 2022-08-22 02:51
Gadgetbridge Pull Request [#2830](https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/2830) created. Instead of exposing the interface as an API, I just made a generic BroadcastReceiver for weather data. Users can use QuickWeather or any app which implements the spec. If Gadgetbridge approves the PR, I'll finish implementing the spec in QuickWeather and release it as part of the next release

**Comment by coxackie** [comment] 2022-08-22 09:04
That's great, as it also makes it easy for other weather apps to follow suit. Let's hope the Gadgetbridge devs act on it soon. They seem to just have released a new version - 0.69.0, so it may take a couple of months for this to appear, even if accepted. Fingers crossed, anyway!

**Comment by TylerWilliamson** [comment] 2022-10-05 23:50
Support added for Gadgetbridge in [2.2.4](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.2.4). Should work with Gadgetbridge 0.71.0 or higher

**Comment by fearlessgeekmedia** [comment] 2022-10-08 22:03
I'm using the version of Gadgetbridge specifically made for the Bangle.js with my Bangle.js 2 watch. It doesn't seem to be working with that. I know Tiny Weather Forecast Germany needs the actual package name for this custom version of Gadgetbridge. Is it possible that could be the issue? It's looking for a different package? The Bangle.js specific version is com.espruino.gadgetbridge.banglejs.

**Comment by TylerWilliamson** [comment] 2022-10-08 22:34
Yes, your Gadgetbridge is not receiving the broadcast because it has a different package name. That is not hard to fix though. Are there any additional package names that you are aware of?

**Comment by fearlessgeekmedia** [comment] 2022-10-08 22:40
I'm not aware of others off the top of my head though there could be more variations of Gadgetbridge. The way Tiny Weather Forecast Germany handles it is by asking the user to put the package name in themselves just in case someone has a custom version of it. If you leave the field blank, it defaults to the normal package name.

**Comment by mskian** [comment] 2022-10-16 07:43
@TylerWilliamson 

Today I got an update for Gadgetbridge
working perfect and Got a Weather update on My MI band 5

**Comment by TylerWilliamson** [comment] 2022-10-16 16:30
@fearlessgeekmedia - [Version 2.2.6](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.2.6) was just released, which should push weather information to all Gadgetbridge variants. Please give it a test (Note: 2.2.6 is available on GitHub, "Open Beta" on Google Play, and will be available on F-Droid as soon as they build again)

Additionally, there were two other Gadgetbridge fixes:

1. The temperatures (especially in Fahrenheit) should be closer to what you are seeing in the app (there was a conversion issue)
2. If your device shows a "tomorrow" forecast (such as my Pebble 2), it will now actually show the "tomorrow" forecast (the daily forecast list should start with tomorrow's forecast, not today's).

Please let me know in this thread if you notice any issues with this feature, such as inaccurate weather on your devices.

**Comment by fearlessgeekmedia** [comment] 2022-10-16 21:47
Awesome. I will give it a try ASAP, probably sometime tonight.

**Comment by fearlessgeekmedia** [comment] 2022-10-16 23:39
Well I'm giving it a try. So far, my watch isn't receiving the weather data
from Gadgetbridge for Bangle.JS though. It's getting other data from
Gadgetbridge for Bangle.JS, however.  Is there any way I can confirm that
QuickWeather is indeed communicating with Gadgetbridge?

**Comment by fearlessgeekmedia** [comment] 2022-10-16 23:41
Actually I just realized Gadgetbridge needed an update too. So I'm doing
that now.

**Comment by fearlessgeekmedia** [comment] 2022-10-16 23:52
OK, it's working now. It took about ten minutes for it to work properly for me, I think.

**Comment by TylerWilliamson** [comment] 2022-10-17 00:29
Glad to hear! I'm closing this issue

**Closed by TylerWilliamson** 2022-10-17 00:29 UTC
Labels: enhancement

**Comment by mskian** [comment] 2022-10-17 04:35
@TylerWilliamson  if possible Update app readme and Gadgetbridge weather wiki docs about QuickWeather Support and usage
