### ISSUE TITLE
Crashing in settings

### ISSUE THREAD

**Issue by ItsRogueRen** [TylerWilliamson/QuickWeather#35] opened 2022-08-12 08:26 UTC
App crashes when going to the last page of the settings after initial setup. Repeated 3-5 times with no change.

Steps to reproduce:
1) install Quick Weather
2) go through the setup
3) after setup is finished, go to the settings
4) hit the next arrow twice to get to the 3rd page

Expected: last settings page for theme/notification should show

Actual: app stops responding (crash)

**Comment by TylerWilliamson** [comment] 2022-08-15 22:42
I am unable to reproduce this error. Could you provide more information, such as a crash log? Alternatively, could you provide the settings that were entered?

If you want to resolve this issue, you can most likely just clear the app data via the Android app settings

**Comment by TylerWilliamson** [comment] 2022-08-19 03:31
Since there is no additional information and I cannot reproduce this, I will be closing the issue. If you are able to provide information to reproduce this, I will re-open

**Comment by TylerWilliamson** [comment] 2022-08-20 02:12
Even though I could not reproduce this, I did thankfully find the crash log in Google Play Console. The fix will be included in the next version released (2.2.2)

**Comment by ItsRogueRen** [comment] 2022-08-31 14:17
Apologies for nor adding more info, it kept slipping my mind.

No settings were entered, everything was default save for the api

Also, I don't know where I would get a crash log. I don't get a dialog option to upload a log after a crash.

**Comment by TylerWilliamson** [comment] 2022-09-20 03:41
Resolved in [2.2.3](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.2.3)

**Closed by TylerWilliamson** 2022-09-20 03:41 UTC
Labels: bug
