### ISSUE TITLE
Monochrome icon?

### ISSUE THREAD

**Issue by coxackie** [TylerWilliamson/QuickWeather#63] opened 2023-01-03 23:55 UTC
I recall there was a mention about monochrome themed icon having been added for the app, but i have two devices with A13 and in both I fail to see it.

**Comment by TylerWilliamson** [comment] 2023-01-04 01:42
I can confirm on my device (Samsung S21+ on Android 13 using the One UI Launcher) that the themeable icon works. Can you confirm your other icons are themed? If so, what decice, Android version, and launcher are you using?

**Comment by TylerWilliamson** [comment] 2023-01-11 23:14
This seems to be a bug of some sort. I'll definitely look into it. Unfortunately, development work is mostly paused right now, but I hope to work on this and other open issues in the second half of 2023

**Comment by TylerWilliamson** [comment] 2023-07-14 21:25
Hello, are you still experiencing this issue? I have been unable to replicate it. Is there a launcher I can test with from the Google Play Store to replicate this issue?

**Comment by coxackie** [comment] 2023-07-14 22:05
Hmmmm, I don't know really, now the launcher I use (still ArrowOS stock launcher based on launcher3) forces monochrome icons (altering them if they are not), so I am not seeing the issue. It does not mean it is not there, of course.

**Comment by TylerWilliamson** [comment] 2023-07-14 22:07
Are you seeing the issue on any of the other devices you mentioned? If not, I will go ahead and close this ticket and we can re-open if you experience the issue again

**Comment by coxackie** [comment] 2023-07-14 22:30
Just tested with my tablet and the issue is still there. Again, stock launcher based on launcher3 on a custom LeafOS rom. Just like in the picture I have sent above. But I do not know any launcher from the play store to suggest.

**Comment by TylerWilliamson** [comment] 2023-07-14 22:36
I may have stumbled onto a potential solution. It turns out that I set the normal icon to have a monochrome layer, but not the "round" icon. I'll make the change and will let you know when it's released. If it works, please let me know and I can close the issue

**Comment by TylerWilliamson** [comment] 2023-07-15 00:07
I have made the change and created an APK for you to test it. You should be able to install it without uninstalling the version from Google Play Store. Please let me know if this fixes the issue

[QuickWeather-2.3.4-PREVIEW.zip](https://github.com/TylerWilliamson/QuickWeather/files/12059508/QuickWeather-2.3.4-PREVIEW.zip)

**Comment by coxackie** [comment] 2023-07-15 15:44
so, something quite funny happened. The icon of the preview app indeed changed to monochrome, but at the same time now the icon for the old (not preview) app changed to monochrome as well. Even after I uninstalled the preview app. Maybe it is a cache issue and it will revert again later. Anyway, it appears that whatever you did worked.

**Comment by TylerWilliamson** [comment] 2023-07-15 17:51
Glad to hear it. I'll be releasing 2.3.4 soon with the fix. I'll update this thread once it's released

**Comment by TylerWilliamson** [comment] 2023-07-15 18:52
Fixed in [2.3.4](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.3.4)

**Closed by TylerWilliamson** 2023-07-15 18:52 UTC
Labels: bug
