### ISSUE TITLE
Theme error since the update to Android 15

### ISSUE THREAD

**Issue by amarradi** [TylerWilliamson/QuickWeather#186] opened 2024-10-25 13:36 UTC
Yesterday I received the update to Android 15 and today I opened quick weather for the first time and discovered the error in the top bar.

![Screenshot_20241025-154006.png](https://github.com/user-attachments/assets/6c33739c-4e06-4e4d-9192-33a678a5105e)

**Comment by TylerWilliamson** [comment] 2024-10-25 15:29
This seems to be a duplicate of #184. Could you confirm what version of QuickWeather you are using? This issue should be resolved in [2.7.4](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.7.4), but if you are still seeing this, then I have more work to do.

**Comment by amarradi** [comment] 2024-10-26 17:29
I have not yet received this version via fdroid. For sure it is solved then

**Comment by TylerWilliamson** [comment] 2024-10-26 20:46
Huh, just noticed that on F-Droid, QuickWeather is still on version 2.6.11. I will look into this and hopefully add some form of push update from this repository to the F-Droid repository, instead of waiting for them to check for updates

**Comment by amarradi** [comment] 2024-10-26 21:52
I just got an update to 2.7.3 via fdroid last week. Maybe it's the regions or the smartphone. Since the update to Android 15 I've had the problems before, everything was fine, even with the 2.7.3 version

![Screenshot_20241026-234841.png](https://github.com/user-attachments/assets/8fc3f57e-78aa-4f2d-82ec-2326fb1b57db)

**Comment by amarradi** [comment] 2024-10-26 21:54
In fdroid i can see the version 2.7.3 and not 2.7.4

![Screenshot_20241026-235342.png](https://github.com/user-attachments/assets/25f13320-020c-44be-beb1-9ac55e1e772a)

**Comment by TylerWilliamson** [comment] 2024-10-27 00:02
The reason that I am seeing the older version is likely because I am still on Android 14. Via the [f-droid site](https://f-droid.org/en/packages/com.ominous.quickweather/) though I can see that they have updated to version 2.7.4. Hopefully, you are able to see the update soon

**Comment by amarradi** [comment] 2024-10-27 22:01
You can close it. In my case the app runs without errors. Today i got the update to 2.7.4

**Comment by TylerWilliamson** [comment] 2024-10-27 22:04
Excellent, thank you. Please let me know if you encounter any other issues on Android 15

**Closed by TylerWilliamson** 2024-10-27 22:04 UTC
Labels: duplicate
